### YamlMime:QSharpType
uid: microsoft.quantum.canon.compose
name: Compose
type: function
namespace: microsoft.quantum.canon
summary: >-
  傳回兩個函數的組合。


  假設有兩個函數 $f $ 和 $g $，則會傳回代表 $f \circ g $ 的新函式。
syntax: "function Compose (outer : ('U -> 'V), inner : ('T -> 'U)) : ('T -> 'V)"
input:
  content: "(outer : ('U -> 'V), inner : ('T -> 'U))"
  types:
  - name: outer
    summary: 要套用的第二個函數。
    isFunction: true
    input:
      types:
      - uid: "'U"
        isLocal: true
    output:
      types:
      - uid: "'V"
        isLocal: true
  - name: inner
    summary: 要套用的第一個函數。
    isFunction: true
    input:
      types:
      - uid: "'T"
        isLocal: true
    output:
      types:
      - uid: "'U"
        isLocal: true
output:
  content: ('T -> 'V)
  types:
  - summary: '新的函式 $h $，用於所有輸入 $x $、$f (g (x) # A3 = h (x) $。'
    isFunction: true
    input:
      types:
      - uid: "'T"
        isLocal: true
    output:
      types:
      - uid: "'V"
        isLocal: true
typeParameters:
- uid: "'T"
  summary: 要套用之第一個函數的輸入類型。
- uid: "'U"
  summary: 要套用之第一個函式的輸出類型，以及要套用之第二個函式的輸入類型。
- uid: "'V"
  summary: 要套用之第二個函數的輸出類型。
metadata:
  ms.openlocfilehash: f2e4d8d10e8113101a5d0ec1f37f8bb7cd0945c0
  ms.sourcegitcommit: 685a8ab16d7e6a25e63a168d6e7c385fa6e876cc
  ms.translationtype: MT
  ms.contentlocale: zh-TW
  ms.lasthandoff: 09/29/2020
  ms.locfileid: "91467162"
